version: '3.1'

services:

 mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017

volumes:
 mongodbdata: